### ISSUE TITLE
A/B root filesystem

### ISSUE THREAD

**Issue by herry13** [fruit-testbed/fruitos#2]
Partition layout:
- partition1: boot -- `vfat`
- partition2: root filesystem A -- `ext4`
- partition3: root filesystem B -- `ext4`
- partition4: data filesystem -- `btrfs`

TODO:
- [x] install software packages of root filesystem on partition2 (A) and partition3 (B) when building the image
- [x] install kernel (`vmlinuz`) and ramdisk (`initramfs`) into directory `/boot` on partition2 (A) and partition3 (B) so that we will have two versions of kernel
- [x] mount `/dev/mmcblk0p1` onto `/media/mmcblk0p1`
- ~~[ ] create subdirectories `/media/mmcblk0p1/A` and `/media/mmcblk0p1/B`~~
- ~~[ ] create a soft link `/boot` referring to `/media/mmcblk0p1/A` on partition2 (A)~~
- ~~[ ] create a soft link `/boot` referring to `/media/mmcblk0p1/B` on partition3 (B)~~
- [x] create a `uboot` package that contains `uboot-rpi` (rpi 0/1/CM), `uboot-rpi2`, `uboot-rpi3` (rpi 3/CM3)
- [x] update `config.txt` to load U-Boot
- [x] create a U-Boot script to do flipflop boot A/B using environment variables to determine **next boot**
- [x] force kernel to reboot if it's panic when booting (set `panic=5` in kernel parameters)

**New fact: U-Boot can load kernel/ramdisk from Ext4 partition!!!**

**Comment by herry13** [comment]
Here are articles/mails/patches around u-boot that might be useful to create a script for A/B booting:

- Pass through start.elf bootargs on Raspberry Pi: https://lists.denx.de/pipermail/u-boot/2015-November/235879.html
- Load kernel from ext4 partition: https://github.com/hypriot/image-builder-odroid-c2/issues/5
- Building u-boot for RPi: https://blog.christophersmart.com/2016/10/27/building-and-booting-upstream-linux-and-u-boot-for-raspberry-pi-23-arm-boards/
- Cannot boot RPi kernel using u-boot on RPi3: https://github.com/raspberrypi/linux/issues/2123
- U-Boot command line parsing: http://www.denx.de/wiki/view/DULG/CommandLineParsing

**Comment by herry13** [comment]
Assume the partition layout is:
- `/dev/mmcblk0p1`
    filesystem: fat32
    files: `/bootcode.bin`, `/start.elf`, `fixup.dat`, `u-boot.bin`, `config.txt`, `boot.src`
- `/dev/mmcblk0p2` -- 1st root filesystem
    filesystem: ext4
    files: `/boot/vmlinuz`, `/boot/initramfs`
- `/dev/mmcblk0p3` -- 2nd root filesystem
    filesystem: ext4
    files: `/boot/vmlinuz`, `/boot/initramfs`

~~Assume that the device tree file (`fdtfile`) has been passed by `start.elf` to U-Boot, and U-Boot itself has loaded the file into memory at `${fdt_addr_r}`, which will be automatically used during kernel booting~~. This assumption is wrong since the file name is hard-coded and it's incorrect.

**TODO: modify below script.**

~~Then the following `boot.cmd` could be used for A/B booting using U-Boot:~~
```
setenv kernel vmlinuz
setenv ramdisk initramfs
setenv boot_prefix /boot
if test "${root}" = "/dev/mmcblk0p2"; then setenv root_dev /dev/mmcblk0p3; setenv root_part "0:3"; else setenv root_dev /dev/mmcblk0p2; setenv root_part "0:2"; fi
setenv bootargs 8250.nr_uarts=1 console=ttyAMA0,115200 console=tty1 noquite loglevel=7 dwc_otg.lpm_enable=0 root=${root_dev} rootfstype=ext4
ext4load mmc ${root_part} ${kernel_addr_r} ${boot_prefix}/${kernel}
ext4load mmc ${root_part} ${ramdisk_addr_r} ${boot_prefix}/${ramdisk}
bootz ${kernel_addr_r} ${ramdisk_addr_r}
```
More complete implementation of `boot.cmd` can be found [here](https://github.com/fruit-testbed/fruitos/blob/uboot/boot.cmd)

The above `boot.cmd` should be compiled into `boot.scr` using command: `mkimage -C none -A arm -T script -d boot.cmd boot.scr`.

Content of `config.txt` is:
```
disable_splash=1
boot_delay=0
gpu_mem=256
gpu_mem_256=64
enable_uart=1
kernel=u-boot.bin
include usercfg.txt
```

See branch [uboot](https://github.com/fruit-testbed/fruitos/tree/uboot) for developments.

**Comment by herry13** [comment]
Version 1a0f1fa87abea7b68f82c763130941a2e2e11fd3 has a working FruitOS with A/B root filesystems.
